version: '3.7'

services:
  reverse_proxy:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # The HTTP port
      - "83:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"      
  app:
    build: .
    container_name: nuxt-app
    restart: always
    ports:
      - '4000:4000'
    command: 'npm run start'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.front.rule=Host(`www.laposte.local`)'
      # - 'traefik.http.routers.front.entrypoints=secure'
      - 'traefik.http.routers.front.tls=true'
    environment:
      - ENV=dev

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '30:80'
  #   depends_on:
  #     - app